version: "3.8"
services:
  neo4j:
    image: neo4j:4.4.3-community
    ports:
      # - 7474:7474  # HTTP port, consider disabling if using HTTPS exclusively
      - 7687:7687  # Bolt port
      - 7473:7473  # HTTPS port
    restart: unless-stopped
    environment:
      NEO4J_AUTH: neo4j/password
      # NEO4J_dbms_connector_https_enabled: true  # Enable HTTPS
      # NEO4J_dbms_ssl_policy_bolt_enabled: true  # Enable SSL for Bolt
      # NEO4J_dbms_ssl_policy_https_enabled: true  # Enable SSL for HTTPS
      # The following lines are necessary if you're using custom SSL certificates.
      # Adjust the paths according to where you place your certificates.
      # - NEO4J_dbms_ssl_policy_bolt_base_directory=/ssl
      # - NEO4J_dbms_ssl_policy_https_base_directory=/ssl
    volumes:
      - ./db/data:/data
      - ./db/conf:/conf
      - ./db/logs:/logs
      - ./db/plugins:/plugins
      # Mount your SSL certificates directory for Neo4j to use, adjust the source path as necessary.
      - ./ssl:/var/lib/neo4j/ssl